Improvements/pp 45260
paypay/paypayopa-sdk-php pull request #36
Opened 2020-09-11 08:58 UTC by paypay-ayas

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing](../../paypayopa-sdk-php/blob/master/contributing.md) document?
* [ ] Have you read and signed the automated Contributor's License Agreement?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../paypayopa-sdk-php/pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you lint your code locally prior to submission?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2020-09-14 08:01 UTC, shreyanshp requested changes

2020-09-14 08:01 UTC, shreyanshp commented on src/Controllers/Payment.php
> +                    'timeout' => $options['CURLOPT_TIMEOUT']
Can we just call it `HTTP_TIMEOUT` or just `TIMEOUT` instead of `CURLOPT_TIMEOUT `?

2020-09-14 08:01 UTC, shreyanshp commented on src/Controllers/Payment.php
> +                    'query' => ['agreeSimilarTransaction' => true],
`agreeSimilarTransaction ` should be `false` everywhere

2020-09-15 01:49 UTC, paypay-ayas commented on src/Controllers/Payment.php
> +                    'query' => ['agreeSimilarTransaction' => true],
@shreyanshp This a code block for when `agreeSimilarTransaction` is enabled.
This is the method signature:
`createPayment($payload, $agreeSimilarTransaction = false)`
 This is the if block:
```php
if ($agreeSimilarTransaction) {
            $response = HttpRequest('POST', $url, ['agreeSimilarTransaction' => true], $data, $options);

            $response = $this->main()->http()->post(
                $url,
                [
                    'headers' => $options["HEADERS"],
                    'json' => $data,
                    'query' => ['agreeSimilarTransaction' => true],
                    'timeout' => $options['CURLOPT_TIMEOUT']
                ]
            );

            return json_decode($response->getBody(), true);
        }
```

2020-09-15 10:50 UTC, shreyanshp approved these changes

2020-09-15 10:51 UTC, shreyanshp requested changes
Why did the unit tests fail?

2020-09-15 11:24 UTC, shreyanshp approved these changes

2020-09-15 11:25 UTC, merged