Pp 49886
paypay/paypayopa-sdk-php pull request #67
Opened 2020-10-29 03:39 UTC by paypay-ayas

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing](../../paypayopa-sdk-php/blob/master/contributing.md) document?
* [ ] Have you read and signed the automated Contributor's License Agreement?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../paypayopa-sdk-php/pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you lint your code locally prior to submission?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2020-11-03 23:02 UTC, shreyanshp submitted a review, later dismissed

2020-11-04 03:49 UTC, paypay-ayas commented on src/Controllers/Payment.php
> +                    'query' => ['agreeSimilarTransaction' => true],
This block of code is executed for call requesting similar transactions. The default is set to false.

2020-11-04 08:26 UTC, solancer approved these changes
LGTM

2020-11-04 10:38 UTC, shreyanshp approved these changes

2020-11-04 10:39 UTC, shreyanshp requested changes
Fix CI

2020-11-04 11:02 UTC, shreyanshp approved these changes

2020-11-04 11:02 UTC, merged