Build ci actions
paypay/paypayopa-sdk-php pull request #85
Opened 2020-12-10 14:10 UTC by javidlulu

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing](../../paypayopa-sdk-php/blob/master/contributing.md) document?
* [ ] Have you read and signed the automated Contributor's License Agreement?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../paypayopa-sdk-php/pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you lint your code locally prior to submission?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2020-12-10 15:52 UTC, ashraf-km approved these changes
approved

2020-12-11 06:30 UTC, shreyanshp requested changes

2020-12-11 06:30 UTC, shreyanshp commented on .github/workflows/build-ci.yml
> +          ./cc-test-reporter before-build
shouldn't this go before Run tests?

2020-12-11 06:30 UTC, shreyanshp commented on .github/workflows/build-ci.yml
> +        run: bash <(curl -s https://copilot.blackducksoftware.com/ci/githubactions/scripts/upload)
I think you have missed codeclimate in post steps, please check the travis.yml once and make sure we have all the scripts and features migrated to github actions

2020-12-11 06:59 UTC, javidlulu commented on .github/workflows/build-ci.yml
> +          ./cc-test-reporter before-build
done

2020-12-14 05:44 UTC, shreyanshp approved these changes

2020-12-14 05:44 UTC, merged